### ISSUE TITLE
source device name or alexa group name for room awareness?

### ISSUE THREAD

**Issue by jpoeppelman1** [csuermann/node-red-contrib-virtual-smart-home#11]
Very cool integration.  Was wondering if there is a way to add the source Echo device name or associated Alexa app group to the node output?  This would enable room awareness!

**Comment by csuermann** [comment]
Thanks for the feedback!

Unfortunately no information about the invoking Echo device or room group is provided by Alexa to the skill backend.

You can of course create room groups in the Alexa app, so that you can generically instruct Alexa to "turn on/off the light" depending on the room you're in.

**Comment by csuermann** [comment]
That's right, it's limited to lights. Unless Amazon updates their smart home skill, there's not much I can do about it, I'm afraid.

**Comment by jpoeppelman1** [comment]
Thanks anyway.  Hopefully Amazon will enhance Alexa to support room contextual awareness.  It would be the icing on the cake!   Thanks again.
