### ISSUE TITLE
Great project! Can you detect which alexa device has sent the request?

### ISSUE THREAD

**Issue by Kiwifranky** [csuermann/node-red-contrib-virtual-smart-home#115]
Is it possible to also return the ID/name of the alexa device the command was initiated. 
It then would be possible to react on this special device by sending a speak command to it.

That would be a great feature!

Nice work - I think I will switch to this solution soon and support it!

**Comment by csuermann** [comment]
Hi @Kiwifranky,

Unfortunately the Alexa Smart Home skill API does not expose information about the Echo device that received a command. However, you can make use of "rooms" to group virtual devices and an Alexa device together so that you can simply say "Alexa, switch off the light". (see [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq))
