### ISSUE TITLE
[FEATURE REQUEST] Use personalization to prevent abuse

### ISSUE THREAD

**Issue by tobi-github** [csuermann/node-red-contrib-virtual-smart-home#116]
Great tool, it works like a charm! But I miss one thing.

I would like to make sure that only household members can control my smarthome components via voice assistant. Alexa offers the option of creating voice profiles and recognizing known people - everyone else is a _stranger_. Unfortunately, this restriction cannot be configured in general.

Here's my workaround: This skill uses personalization and optionally inserts the name of the person of the voice profile into the payload - or _stranger_ if the person is unknown. So we have the option to discard the command of unkown people, for example.

More infos: https://developer.amazon.com/en-US/docs/alexa/custom-skills/add-personalization-to-your-skill.html

Demo: https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-personalization

Viele Grüße nach Berlin

**Comment by csuermann** [comment]
Hi @tobi-github,

That would be a nice feature indeed. Unfortunately this would require a complete rewrite of VSH because personalization is only supported for "custom skills" and not for the "smart home skill" that VSH is leveraging. And a custom skill based implementation would have major downsides, e.g. users would have to mention the skill name for every voice command, e.g. "Alexa, _ask virtual-smart-home_ to switch off the kitchen light", which would make VSH far less usable.
