### ISSUE TITLE
Activating the Virtual Smart Home skill 

### ISSUE THREAD

**Issue by scargill** [csuermann/node-red-contrib-virtual-smart-home#14]
Hi I wonder if you can advise. I've just beeen talking to a guy (friend of mine - Antonio) who you;ve just helped with a sample flow or similar - that's not my issue. Indeed not your node at all - in order to use your node, we neeed to activate the virtual smart home skill in the Alexa App. I simply cannot get past that point.

So, on my smartphone, logged into Alexa (which I use all the time and have lots of lights and controllers etc) today I've tried activating the skill - I'm told by Alexa App (Android) that this will need account linking - I told it to go ahead (firstly without a UK VPN as I'm in Spain) then WITH a UK VPN - in both cases skills.store.amazon.co.uk says "we were unable to link at this time - try later" or similar. Thoughts?

**Comment by csuermann** [comment]
Hi Peter,

Thanks for reaching out! Unfortunately I couldn't find any hint in the server logs. I'm guessing this might have to do with some sort of timeout, but I cannot really debug it from Germany. 

Could you please try the following?

- Use the [Spanish skill store](https://www.amazon.es/dp/B08JV9RT7H/?ref-suffix=ss_copy)
- Instead of using your phone, initiate the account linking process from [your computer](http://alexa.amazon.com/). If that doesn't work either, inspecting the network traffic might reveal some helpful hints.
- Retry another account linking process shortly after the first one failed
- Send me a screenshot of the error screen including exact time of the failed attempt

Thanks for your support!

Best Regards
C.

**Comment by scargill** [comment]
> Hi Peter,
> 
> Thanks for reaching out! Unfortunately I couldn't find any hint in the server logs. I'm guessing this might have to do with some sort of timeout, but I cannot really debug it from Germany.
> 
> Could you please try the following?
> 
> * Use the [Spanish skill store](https://www.amazon.es/dp/B08JV9RT7H/?ref-suffix=ss_copy)
> * Instead of using your phone, initiate the account linking process from [your computer](http://alexa.amazon.com/). If that doesn't work either, inspecting the network traffic might reveal some helpful hints.
> * Retry another account linking process shortly after the first one failed
> * Send me a screenshot of the error screen including exact time of the failed attempt
> 
> Thanks for your support!
> 
> Best Regards
> C.

Thanks for the quick response. I'm not sure how but eventually the UK store accepted my attempt.  All is well.

**Comment by csuermann** [comment]
Glad to hear it worked out in the end.

My hypothesis: Login with Amazon (LWA) seems to be rather slow sometimes, even slower than what Amazon defined as a threshold for Alexa skill activation. This could be the reason behind your broken experience.
