### ISSUE TITLE
UPCOMING CHANGES

### ISSUE THREAD

**Issue by csuermann** [csuermann/node-red-contrib-virtual-smart-home#148]
## Dear VSH community!

When I launched VSH I had no idea that two years later the project would be used by several thousand users. While I am truly thankful for all the appreciation, feedback and generous donations, VSH is more and more becoming a victim of its own success: The number of active users directly correlates with the amount of money Amazon AWS charges me each month.

**By now my AWS bills are exceeding what I feel comfortable sponsoring as a private person.**

I will therefore implement the following changes that should drastically reduce the number of MQTT messages exchanged between all your Node-RED instances and my VSH backend, and in turn lead to a reduction in cost that will make my prolonged sponsorship possible:

1. Going forward, your VSH devices will no longer be "retrievable" by Alexa, hence you will no longer be able to see the current state of your devices in the Alexa app. This will _not_ impact the ability to control your VSH devices using your voice or via the app.

2. The number of VSH devices per user will be limited to 7.

3. Depending on demand, I will offer a moderately priced "Pro" version of VSH which comes with unlimited devices that are also retrievable, effectively eliminating the restrictions introduced in 1. and 2.

I hope I managed to explain the rationale behind these decisions. Let me know if you have any feedback or suggestions.

**Comment by 8none1** [comment]
I'm interested in a pro version.

**Comment by csuermann** [comment]
@8none1, long term sponsors of this project (like you), will of course get the first year of the pro version without having to purchase a subscription. I don't intend to optimize for profit, hence pricing will be around 1 EUR / 1 USD per month.

**Comment by thermseekr** [comment]
Hi, I would sign to a pro version.
I’m curious, do you mind sharing how much do you currently spend with AWS regarding VSH?

Enviado do meu iPhone

**Comment by csuermann** [comment]
Hi @thermseekr, I'd rather not go into details but keep it as:

> By now my AWS bills are exceeding what I feel comfortable sponsoring as a private person.

**Comment by steff75** [comment]
Only 9 sponsors with several thousand users is a bit sad.

I would definitely join a pro version for ~1€/$ per month.

**Comment by csuermann** [comment]
Thank you, @steff75! To be fair, the GH sponsorship option is not very visible if you're just using the VSH package. Some people donate via PayPal, too.

**Comment by Heurigl** [comment]
Dear Cornelius,
I also would like to support, and get the pro-Version.

**Comment by myervin** [comment]
Guten tag, did not know sponsorship was an option, I do now and will also be happy to support and pay for the pro version. Excellent work!

**Comment by hawkseye76** [comment]
I'm in for the pro version even though I probably don't need it.  This module is one of my favorites!

**Comment by brunialti** [comment]
It sound reasonable. Please, when there will be  the switch to pro version.Let it also seeable by node red, otherwise I could spend hours trying to understand why my flows does'nt work :-)
Let me catch this opportunity to ask for some more infos:
- I really do not need the devices are discoverable by alexa (as i manage all the requests within NR) , neverthless I'm not able to undestand which are the functionality impacted, if any.
- actually I have a disappointing behaviour: I have a thermometer device in my home automation setup, so I create a VHS device (thermometer type) in order to avoid "device not found" message by alexa. Unfortunately this starts an unavoidable  message by alexa trying to answer with the current VHS temperature value , instead of let my NR flow to manage my answer with my own custom message. Is there a way to silent/shutup/trap such alexa messages?

**Comment by csuermann** [comment]
Hi @brunialti,

Absolutely, I'll try to make the migration as seamless as possible.

> I really do not need the devices are discoverable by alexa (as I manage all the requests within NR and I do not need Alexa answers) , nevertheless I'm not able to understand which are the functionality potentially impacted, if any.

As long as you do not need to be able to ask Alexa (or the Alexa app) for the state of your devices, the limitation of "unretrievable device state" should not be an issue for you.


> actually I have a disappointing behaviour: I have a thermometer device in my home automation setup, so I create a VHS device (thermometer type) in order to avoid "device not found" message by alexa. Unfortunately this starts an unavoidable message by alexa trying to answer with the current VHS temperature value , instead of let my NR flow to manage my answer with my own custom message. Is there a way to silent/shutup/trap such alexa messages?

Not sure I understand this fully yet. What do you mean by "to avoid "device not found" message by alexa"? VSH is built on top of Alexa's smart home skill API which also determines the interaction phrases and Alexa's responses.

**Comment by brunialti** [comment]
> Not sure I understand this fully yet. What do you mean by "to avoid "device not found" message by alexa"? VSH is built on top of Alexa's smart home skill API which also determines the interaction phrases and Alexa's responses.

In my alexa NR flow I catch the alexa request receiving a STT (speach to text) message, then I parse the request text, I perform the requested actions answering , if necessary, via a TTS message. E.g. if you prompt alexa for a sensor value it is necessary install a VHS (dummy) device with the same name of the  device you invoke in yout alexa request, otherwise alexa will answer "cannot find device X" before I am able to format my custom answer and to send it to echo device. 
If you create such a dummy VHS device of type "thermometer" the echo device will immediately try to read the requested value (in this case temperature) of the VHS device and will start to answer "The temperature of X is..." before my custom answer interrupt it with my custom answer.
My question is: how is it possible, if it is, to avoid Alexa to answer me, leaving my flow to manage all my responses?

**Comment by brunialti** [comment]
I'm sorry it is not clear to me what do you mean for "what voice prompts to you say to trigger your routine". Do you mean "how do you activate an alexa routine"? I have to create an empty routine in Alexa, to avoid any feedback message, then the NR flow manage performs all the actions of the routine. It is not trivial to discriminate between alexa "homeAutomation" and "routine" invocation btw...
An example of a customized message on an indoor thermometer type node is the one in which, in addition to the temperature, the message also reports the humidity and possibly the external temperature.

**Comment by csuermann** [comment]
got it, thanks for explaining.

**Comment by csuermann** [comment]
Closing this announcement issue. VSH version 3 is about to get released.
