### ISSUE TITLE
Cannot upgrade to 3.0.1

### ISSUE THREAD

**Issue by brunialti** [csuermann/node-red-contrib-virtual-smart-home#159]
**Describe the bug**
I updated the palette with the latest version.
In the top of the z2m windows appears the warning: Node-RED must be restarted to enable upgraded modules
I restarted z2m, restarted the computer and the browser. I cannot see how to upgrade (looking at the connection panel)

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.1.
 - Node-RED version: 3.0.2

**Comment by csuermann** [comment]
Could you please attach some screenshots? Thank you!

**Comment by brunialti** [comment]
Now i get also limit excedeed with my only 7 devices...
![oh-la 1](https://user-images.githubusercontent.com/1572972/193143047-09f4609f-d3c7-49e5-8d34-ce56b46130d6.JPG)

**Comment by csuermann** [comment]
Hi @brunialti,

Thanks for the screenshots! Looks like the update got installed successfully but is not in effect since Node-RED (running on 192.168.1.165) was not yet restarted?!

You seem to be running into the device limit due to some of your devices showing up as duplicates. The ones with a shaded background were registered via a different vsh-connection. You can delete / unregister them by clicking the trash icon. Please ensure that you have only one vsh-connection configured.

**Comment by brunialti** [comment]
I resolved the problem of the warning (I erroneously restarted a previous version of NR).
I deleted the exceeding nodes and I recreated them but still they seem to be exceeding

**Comment by csuermann** [comment]
Deleting the nodes from Node-RED is not enough. You need to _deregister_ them from the "Registered devices" list in the vsh-connection dialog by clicking the trash icon, as mentioned above.

I checked the database and your account still shows a total of 10 virtual devices connected through 2 different connections (Thing-ID `vsht-089fa874...` and `vsht-5fe4369a...`)

**Comment by brunialti** [comment]
OK. Now it works.
I created a second connections when It was impossible to update the contrib.
Now I deleted the second connection, unregistered all devices and inserted them again.
Now it works. Thank you
