### ISSUE TITLE
Questions regarding Subscription Procedure

### ISSUE THREAD

**Issue by dcbo** [csuermann/node-red-contrib-virtual-smart-home#171]
Hi Cornelius, 

I have four little questions regarding the subscription procedure:

1) I would like to upgrade to the PRO plan, but I wonder if I can change the E-Mail Address I have to register, 
I use separate E-Mails for each service, and i don't want to spread the E-Mail i used for Amazon to other systems. 

2) I have to switch to another Alexa account during the next year, do I have to pay for a second subscription?

3) Is it possible to use Paypal or SEPA?

4) How can i cancel the subscription?

Greetings from Bochum, Germany

Dario

**Comment by csuermann** [comment]
Hi Dario,

Thanks for reaching out!

> I would like to upgrade to the PRO plan, but I wonder if I can change the E-Mail Address I have to register, I use separate E-Mails for each service, and i don't want to spread the E-Mail i used for Amazon to other systems.

Unfortunately that's not yet possible. 

> I have to switch to another Alexa account during the next year, do I have to pay for a second subscription?

You could go for the monthly subscription and cancel the no longer needed one. Or you could send me an email to vsh@csuermann.de with your "Thing ID" so that I can initiate a manual refund. No need to pay twice ;-)

> Is it possible to use Paypal or SEPA?

Stripe unfortunately doesn't support PayPal. They do theoretically provide SEPA support, but it requires more effort to integrate and all sorts of follow-up headaches (e.g. chargebacks). That's why I shied away from it so far.

> How can i cancel the subscription?

You can cancel from within your Node-RED instance or via the [Stripe Customer Portal](https://billing.stripe.com/p/login/6oE00vdQ62Tp3LidQQ). See [FAQ 18](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq).

Hope that helps!

Best,
Cornelius

**Comment by dcbo** [comment]
So I will subscribe yearly and if i change, for me there will be no need for a refund.
I like the Service, and i can afford to pay twice.

Thanks
