### ISSUE TITLE
[BUG] Devices are not found by Alexa / Plan unknown

### ISSUE THREAD

**Issue by Torsten1986** [csuermann/node-red-contrib-virtual-smart-home#179]
**Describe the bug**
Yesterday I Upgraded my Subscription to a Pro Version and deleted all my old Linked Devices, to add them again
But they are not showing in the Alexa App or under Linked Devices. Some of the Devices are showing up but even they are telling me that the Plan is UNKNOWN

**To Reproduce**

**Expected behavior**
Devices work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/1320942/211381583-630ea8ba-fa33-4b8b-9a27-b49f542e0693.png)

![image](https://user-images.githubusercontent.com/1320942/211381270-b3c0f254-997d-437f-af29-415a83539b9c.png)

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.7
 - Node-RED version: 3.0.2

**Additional context**
iOBroker with Nodered are deployed in a docker container with ports open 8081 and 1880

**Comment by Torsten1986** [comment]
Docker Container has internet Access and can ping Google

![image](https://user-images.githubusercontent.com/1320942/211381777-bfd3c39e-333b-49ba-9583-65413b3bb8d5.png)

**Comment by csuermann** [comment]
Hi @Torsten1986,

re-adding devices after signing up for the Pro plan isn't needed as the changes will be picked up automatically. But there seems to be a strange edge case sometimes preventing the plan from being displayed correctly on the vsh-device screen after upgrading. Restarting Node-RED usually fixes it, though.

Since you already closed this issue, how did you manage to resolve it?
