### ISSUE TITLE
Invalid Properties: Connection

### ISSUE THREAD

**Issue by H-K-47** [csuermann/node-red-contrib-virtual-smart-home#38]
I followed the step by step guide on activating the Skill and using the Code to authenticate - but during deployment i get a warning that the vsh virtual device is not correctly configured. But i don't see what could be possible wrong with the connection because i created a new one just entering a Name - then went to the code side and entered the code.

I don't see any messages in the console.

For reference - i'm using the nodered docker image - is there a specific inbound port that needs to be opened?

**Comment by csuermann** [comment]
Hi @H-K-47,

No inbound port needs to be opened. VSH connects to the server via MQTT on port 8883.

Your description sounds like you're running into this warning, correct?
![image](https://user-images.githubusercontent.com/10939809/107141719-0bf44480-692b-11eb-990c-0412aac87e0b.png)

When you open the connection edit dialogue, you'll probably still see an account linking code, correct? If that's the case, the linking process has not been completed yet, e.g. because you clicked the "update" button and closed the dialogue _after_ entering the code on https://amazon.com/us/code, but _before_ the edit dialogue in Node-RED refreshed to display the "Thing-ID".

If my hypothesis is correct, you should be able to fix it by simply attempting the account linking process again and _waiting_ to see the Thing-ID being displayed before clicking the "update" button in Node-RED.

Let me know if this did the trick for you. Might be interesting for others, too.

**Comment by H-K-47** [comment]
Thank you - I was not aware that i had to keep waiting after entering the Code in the Connection Dialog - maybe i didnt read the description correctly but as a suggestion: maybe put a fat RED label "before clicking update wait till this dialog changes to your account ID" or something.

1. While I'm at it - is it possible to have one node provide input for multiple virtual devices? Instead of creating dozens of nodes i would prefer having a function afterwards where i can relay the information according to the msg.payload.name parameter. E.g. "Alexa" is a hub which is the inbound connection node for all my virtual devices. The configuration would be having a list of names for lights or even a key/type list.

I'm using the skill in my KNX env and i would rather "program" code for a complete house Lightning Setting than having tons of WYSIWG editor nodes.

2. I think i read this somewhere but its not possible to define rooms/devices because the API doesnt allow - correct? Rather than naming my devices "Kitchen light" "Bath light" i just want to have it all "light" and depending on the room of the echo/dot/alexa devices it would know which light i mean.

**Comment by csuermann** [comment]
Hi @H-K-47,

I changed the dialog to outline the required steps a bit more clearly, like so:
![image](https://user-images.githubusercontent.com/10939809/107150912-5cd26000-6960-11eb-8cf7-420693cc967d.png)

1. The current architecture of VSH doesn't allow the "hub"-based approach that you describe. I see the benefit of such an approach for rather advanced use-cases like yours, but the 1:1 relationship between a virtual device and a vsh node works quite intuitively for most users.

2. You can group virtual lights and echo devices into a "room" via the Alexa app. This allows you to issue commands like "Alexa, switch off the light", which will be applied to all lights that are part of the room.

Hope that helps!

Best Regards
Cornelius

**Comment by H-K-47** [comment]
Hey, thanks for Feedback. I like the changes from an end user/first time user point of view.

Small suggestion otherwise this can be closed - on step 3 you say "...for this message to disappear" - in the first case, I wouldn't know what "message" you are referring to - from the amazon site? because there is no message just a dialog with a description... maybe something along "Wait till this dialog window refreshes with your account data, usually within 30 seconds" - otherwise if nothing happens some people will still proceed after 30sec - so they would need to check for errors etc

**Comment by csuermann** [comment]
that's good feedback! Thank you! I will release an improved version shortly.
