### ISSUE TITLE
Add Alexa Device ID to Message

### ISSUE THREAD

**Issue by niklasfink** [csuermann/node-red-contrib-virtual-smart-home#44]
Hey @csuermann,

it would be great if the Alexa deviceid would be sent with each message coming into the VSH nodes. That would enable device specific actions, like having a generic "lights" VSH node, which controls different lights depending on the Alexa device which sent the command.

Example: You're in the kitchen and say "Alexa, lights off" -> kitchen lights go off. If you say the same command in the living room, the living room lights would react, as the deviceid of the living room Alexa would be sent and a different nodered flow can go off.

It seems to be possible that custom skills receive the deviceid of the Alexa device which received the verbal command. Maybe this is a point to start: https://developer.amazon.com/en-US/docs/alexa/custom-skills/device-address-api.html#get-the-api-access-token-and-device-id

**Comment by csuermann** [comment]
Hi @niklasfink,

Since VSH is using Amazon's pre-built smart-home skill, the skill backend does not receive any information about the Alexa device that received your voice command. But you can still accomplish what you want!

I just added this section to the FAQ:

> Q: How can I control devices in a specific room?
> 
> A: You can create rooms in the Alexa app and assign your devices to them. Create a room which groups together an Alexa device (e.g. Echo) and some virtual lights. You can then control all those lights simply by speaking "Alexa, switch off the light" into the Alexa device.

This works for lights and probably for some other device types, too (e.g. blinds).

Hope that helps!
