### ISSUE TITLE
[FEATURE REQUEST] ContactSensor

### ISSUE THREAD

**Issue by Maui2k** [csuermann/node-red-contrib-virtual-smart-home#48]
Hi @csuermann,

I'am still loving your solution and setting up more and more devices :-)

What I want to do now is, to use my contact sensors at the windows to trigger routines in the alexa app. As far as I've seen it is not possible to use switches or plugs for that. In the documentation I've found, that there are [ContactSensors ](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-contactsensor.html) under the SmartHome Securtiy Skills

 Would it be possible to integrate them into vsh?

Kind regards
Maui2k

**Comment by csuermann** [comment]
Hi @Maui2k,

Glad to hear you're still a happy user :-)

I will look into implementing a virtual Contact Sensor.

When I first wanted to publish the VSH skill, Amazon pushed back on some of the security related smart home features I had built in and asked me to remove those (e.g. Door Opener). I have not understood why, but cooperated in order to get the skill published. It's possible that I run into the same issue again for the Contact Sensor.
