### ISSUE TITLE
Register account and devices through the dashboard

### ISSUE THREAD

**Issue by tcsaavedra** [csuermann/node-red-contrib-virtual-smart-home#59]
I would like to create all the device nodes in my flows and create Rpi images for end-users. They will need to create their own vsh account through the dashboard and the register each device node through the dashboard instead of having them open node-red and do it by double-clicking on each device node. The end-users may not be technically competent to do that. Is there a web page they can register for a vsh account instead of directly in the node? Can I then use their Amazon account info and put it in the global variable for vsh? Will the devices then use that connection and register each device when the flow is deployed?

**Comment by csuermann** [comment]
Hi @tcsaavedra,

Besides the account linking, there is actually more going on behind the scenes: Each vsh-connection gets provisioned its own certificate and registered with the backend. Hence I don't think there is an easy way to accomplish what you want to do.

Since the [backend source code](https://github.com/csuermann/virtual-smart-home/tree/sandbox) is also available, you can of course fork it and tweak it to your needs.
