### ISSUE TITLE
[BUG] VSH becomes unavailable each night.

### ISSUE THREAD

**Issue by dthiessen2** [csuermann/node-red-contrib-virtual-smart-home#78]
**Describe the bug**
Since upgrading to 2.01 (now 2.02 also) VSH will stop working overnight.
Each morning since upgrading no alexa voice command that uses VSH will work.
Alexa will respond with something along the lines of "the hub does not respond".
In Nodered everything seems fine, all VSH nodes show up as connected, no errors are shown
and everything else still works. 
Redeyploying the flows will fix the issue until next morning.
No changes were done to the flos other than upgrading VSH.

**To Reproduce**
1. i just have to wait 24hours for it to stop working (sorry not very helpfull i know)

**Expected behavior**
VSH should stay available without redeploying the flows every day.

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.0.2
 - Node-RED version: 1.2.9

**Comment by csuermann** [comment]
Hi @dthiessen2,

Sorry to hear your VSH is misbehaving!

Since v2 the skill backend checks whether the device is marked as connected in the shadow database before attempting to forward a directive to your device. If your connection breaks (e.g. due to an enforced internet provider disconnect) the state in the backend database will be set to disconnected. It should however get set to connected again, as soon as your device re-connects.

Could you please switch on debug mode for the vsh-connection node and observe the output logged to stdout?

**Comment by dthiessen2** [comment]
Thank you for the fast reply.
I have tried to simulate this by prohibiting the raspberry pi from accessing the internet.
It has reconnected without problems however.

I will check the logs tomorrow morning if the issue reappears then.

**Comment by dthiessen2** [comment]
This issue has not resurfaced again.
I'll close the ticket for now.
Thanks again!
